import { useEffect, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowUp, Check, ChevronRight, Cpu, HardDrive, MemoryStick, Network, Pencil, Server, Settings2, Trash2, X } from "lucide-react";
import type { NodeSnapshot } from "../types";
import { formatBytes, formatOperatingSystem, formatPercent, formatRate, formatRelativeTime, nodeDiskPercent, nodeMemoryPercent } from "../utils";
import { browserLatencyLabel, type BrowserLatency } from "../hooks/useBrowserLatency";
import { ConfirmDialog } from "./ConfirmDialog";
import { MonitoringPanel, type DetailTab } from "./MonitoringPanel";
import { NodeOverview } from "./NodeOverview";
import { HistoryRangeControl, HistoryRangeProvider, type HistoryMinutes } from "./HistoryRange";
import "./NodeDetail.css";

interface NodeDetailProps { node: NodeSnapshot; onBack: () => void; onDelete: (nodeId: string) => Promise<void>; onRename: (nodeId: string, displayName: string) => Promise<NodeSnapshot>; onUnauthorized: () => void; browserLatency?: BrowserLatency; onConfigSaved: () => void; initialTab?: DetailTab; onTabChange?: (tab: DetailTab) => void; refreshKey?: number }

export function NodeDetail({ node, onBack, onDelete, onRename, onUnauthorized, browserLatency, onConfigSaved, initialTab = "overview", onTabChange, refreshKey = 0 }: NodeDetailProps) {
  const [tab, updateTab] = useState<DetailTab>(initialTab); useEffect(() => updateTab(initialTab), [initialTab]);
  const setTab = (value: DetailTab) => { updateTab(value); onTabChange?.(value); };
  const [minutes, setMinutes] = useState<HistoryMinutes>(60); const [editing, setEditing] = useState(false); const [name, setName] = useState(node.display_name || node.hostname); const [saving, setSaving] = useState(false); const [nameError, setNameError] = useState<string | null>(null); const [confirming, setConfirming] = useState(false); const [deleting, setDeleting] = useState(false); const [deleteError, setDeleteError] = useState<string | null>(null);
  const latest = node.latest;
  const saveName = async () => { if (!name.trim() || saving) return; if (new TextEncoder().encode(name.trim()).length > 64) { setNameError("主机名称不能超过 64 字节"); return; } setSaving(true); setNameError(null); try { await onRename(node.id, name.trim()); setEditing(false); } catch (error) { setNameError(error instanceof Error ? error.message : "无法修改名称"); } finally { setSaving(false); } };
  const deleteNode = async () => { if (deleting) return; setDeleting(true); setDeleteError(null); try { await onDelete(node.id); onBack(); } catch (error) { setDeleteError(error instanceof Error ? error.message : "无法删除主机"); } finally { setDeleting(false); } };
  return <HistoryRangeProvider minutes={minutes} setMinutes={setMinutes} refreshKey={refreshKey}>
    <article className="node-inspection" aria-label={`${node.display_name || node.hostname} 主机详情`}>
      <nav className="inspection-breadcrumb" aria-label="详情位置"><button type="button" onClick={onBack}><ArrowLeft size={14} />主机</button><ChevronRight size={12} /><span>{node.group_name || "未分组"}</span></nav>
      <header className="inspection-heading"><span className="inspection-device-icon"><Server size={23} strokeWidth={1.6} /></span><div className="inspection-identity"><div className="inspection-name-row">{editing ? <div className="inspection-name-editor"><input aria-label="主机名称" value={name} maxLength={64} autoFocus disabled={saving} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void saveName(); if (event.key === "Escape" && !saving) setEditing(false); }} /><button type="button" className="icon-button" title="保存名称" aria-label="保存名称" disabled={saving || !name.trim()} onClick={() => void saveName()}><Check size={15} /></button><button type="button" className="icon-button" title="取消修改" aria-label="取消修改" disabled={saving} onClick={() => setEditing(false)}><X size={15} /></button></div> : <h1>{node.display_name || node.hostname}</h1>}<span className={`inspection-online ${node.online ? "online" : "offline"}`}><i />{node.online ? "在线" : "离线"}</span></div><div className="inspection-meta"><span>{node.hostname}</span><span>{formatOperatingSystem(node.os, node.os_version)}</span><span>{node.architecture}</span><span>Agent {node.agent_version}</span></div></div><div className="inspection-tools"><button type="button" className="icon-button" title="修改主机名称" aria-label="修改主机名称" disabled={editing} onClick={() => { setName(node.display_name || node.hostname); setNameError(null); setEditing(true); }}><Pencil size={15} /></button><button type="button" className={`icon-button ${tab === "config" ? "active" : ""}`} title="监测配置" aria-label="监测配置" aria-pressed={tab === "config"} onClick={() => setTab("config")}><Settings2 size={17} /></button><button type="button" className="icon-button inspection-delete" title="删除主机" aria-label="删除主机" onClick={() => { setDeleteError(null); setConfirming(true); }}><Trash2 size={16} /></button></div></header>
      {nameError && <p className="form-error" role="alert">{nameError}</p>}<div className="inspection-connection"><span><i className={node.online ? "live" : ""} />{node.online ? "最近上报" : "最后上报"} {formatRelativeTime(node.last_seen_at)}</span><span>访问者延迟 <strong title="当前浏览器直接访问此主机 HTTPS 测点的 HTTP 往返耗时">{browserLatencyLabel(browserLatency)}</strong></span></div>
      <section className="inspection-metrics" aria-label={node.online ? "最新上报指标" : "最后上报指标"}><div className="inspection-metric"><span><Cpu size={15} />CPU 使用率</span><strong>{formatPercent(latest?.cpu_percent, 1)}</strong><small>{latest?.monitoring?.cpu_cores.length ? `${latest.monitoring.cpu_cores.length} 个逻辑核心` : latest ? "主机总使用率" : "等待采样"}</small></div><div className="inspection-metric"><span><MemoryStick size={15} />内存使用率</span><strong>{latest ? formatPercent(nodeMemoryPercent(node), 1) : "--"}</strong><small>{formatBytes(latest?.memory_used_bytes)} <em>/</em> {formatBytes(latest?.memory_total_bytes)}</small></div><div className="inspection-metric"><span><HardDrive size={15} />磁盘使用率</span><strong>{latest ? formatPercent(nodeDiskPercent(node), 1) : "--"}</strong><small>{formatBytes(latest?.disk_used_bytes)} <em>/</em> {formatBytes(latest?.disk_total_bytes)}</small></div><div className="inspection-metric inspection-network"><span><Network size={15} />网络吞吐</span><strong><ArrowDown size={14} />{formatRate(latest?.network_received_bytes_per_sec)}</strong><small><ArrowUp size={12} />{formatRate(latest?.network_transmitted_bytes_per_sec)}</small></div></section>
      <MonitoringPanel node={node} tab={tab} onTabChange={setTab} onUnauthorized={onUnauthorized} onConfigSaved={onConfigSaved} browserLatency={browserLatency} toolbar={tab !== "config" ? <HistoryRangeControl minutes={minutes} onChange={setMinutes} /> : null} overview={<NodeOverview node={node} onUnauthorized={onUnauthorized} />} />
      {confirming && <ConfirmDialog title="删除主机？" description={`将删除“${node.display_name || node.hostname}”及其监测历史。`} busy={deleting} error={deleteError} onCancel={() => { if (!deleting) setConfirming(false); }} onConfirm={() => void deleteNode()} />}
    </article>
  </HistoryRangeProvider>;
}
